settings {
   pidfile    = "/tmp/lsyncd_patientwhisperer_sherlock.pid",
   logfile    = "/tmp/lsyncd_patientwhisperer_sherlock.log",
   statusFile = "/tmp/lsyncd_patientwhisperer_sherlock.status",
   nodaemon   = false,
}

sync {
  default.rsync,
  source = "/home/moritz/code/patientwhisperer/",
  target = "sherlock:/home/users/moritzs/patientwhisperer/",
  delay = 3,
  exclude = { '*.h5ad', '.snakemake', '.venv', '.mypy_cache', 'wandb', 'artifacts', 'build', "*.so", "__pycache__", ".#*", "node_modules", "results", ".git", ".pixi", "scratch", "data/patients", "data/spatial_features", "data/infusion_features" },
  rsync = {
    archive = true,
    compress = false
  },
  delete = false
}

sync {
  default.rsync,
  source = "/home/moritz/code/patientwhisperer/",
  target = "ilc:/sailhome/moritzs/patientwhisperer/",
  delay = 3,
  exclude = { '*.h5ad', '.snakemake', '.venv', '.mypy_cache', 'wandb', 'artifacts', 'build', "*.so", "__pycache__", ".#*", "node_modules", "results", ".git", ".pixi", "scratch", "data/patients", "data/spatial_features", "data/infusion_features" },
  rsync = {
    archive = true,
    compress = false
  },
  delete = false
}
