settings {
   pidfile    = "/tmp/lsyncd_patientwhisperer_option-bc.pid",
   logfile    = "/tmp/lsyncd_patientwhisperer_option-bc.log",
   statusFile = "/tmp/lsyncd_patientwhisperer_option-bc.status",
   nodaemon   = false,
}

sync {
  default.rsync,
  source = "/home/moritz/code/patientwhisperer_option-bc/",
  target = "ilc:/sailhome/moritzs/patientwhisperer_option-bc/",
  delay = 3,
  exclude = { '*.h5ad', '.snakemake', '.venv', '.mypy_cache', 'wandb', 'artifacts', 'build', "*.so", "__pycache__", ".#*", "node_modules", "results", ".git", ".pixi", "scratch", "data/patients", "data/spatial_features", "data/infusion_features" },
  rsync = {
    archive = true,
    compress = false
  },
  delete = false
}
